version: '3'
services:
  web:
    depends_on:
      - cache
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
  cache:
    image: redis:3.2-alpine
    volumes:
      - .redis:/data