# - version: unique identifier/version number (increment for each new announcement)
# - type: alert type (info, success, warning, danger) - defaults to 'info'

announcements:
  - version: 1
    message: "" # Message moved to locales for better i18n support
    type: "info"
