free: 
    id: 1
    name: _('Free Plan')
    description: _('Our free plan in which you can use everything in Odonto.me for up to 500 patients')
    number_of_patients: 500

standard:
    id: 2
    name: _('Standard Plan')
    description: _('A great value plan for up to 1000 patients')
    button_partial: standard_button
    price: 9.99
    number_of_patients: 1000

premium:
    id: 3
    name: _('Premium Plan')
    description: _('For practices that have more than 1000 patients. You can register up to 5000!')
    button_partial: premium_button
    price: 19.99
    number_of_patients: 5000
