# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &defaults
  secret_key_base: 9d029dc685fbbdf7845894b0f826aa903afdf0ae8c1142e509fa6353ceba635ac515418e9c20ef0c95849ca067d3b2dfd7d80970c82338b0ce12c09a5e43b18d
  stripe_publishable_key: pk_test_lcbdtn4nPblE0uYMkqGLy7GJ
  stripe_secret_key: sk_test_51DsJT5ABOdzKVszlRXjo2ZmUGJrZOJWnBU9XTjBIxgG7IUiiQpUq7loiRlNAjbRdM8lM4Qg9m4xBzQZQ8iaSJtUI00Mm54VHRZ
  stripe_webhook_secret: whsec_a46e605bda4b3d6d231d4d62c6149fc90f49d1e7ff07630a3d196ccbd68e11f6
  stripe_price_id: price_1JRPagABOdzKVszlVznnsr4Y
  simple_file_upload_key: 42fa40538034d3f39be11
  simple_file_upload_api_public_key: <%= ENV["SIMPLE_FILE_UPLOAD_API_PUBLIC_KEY"] %>
  simple_file_upload_api_secret_key: <%= ENV["SIMPLE_FILE_UPLOAD_API_SECRET_KEY"] %>

test:
  <<: *defaults

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_webhook_secret: <%= ENV["STRIPE_WEBHOOK_SECRET"] %>
  stripe_price_id: <%= ENV["STRIPE_PRICE_ID"] %>
  simple_file_upload_key: <%= ENV["SIMPLE_FILE_UPLOAD_KEY"] %>
  simple_file_upload_api_public_key: <%= ENV["SIMPLE_FILE_UPLOAD_API_PUBLIC_KEY"] %>
  simple_file_upload_api_secret_key: <%= ENV["SIMPLE_FILE_UPLOAD_API_SECRET_KEY"] %>
