en:
  treatments: 
    - Apiectomy
    - Braces
    - Bridge
    - Dental Crown
    - Dental Examination
    - Dentures-Full
    - First Consultation
    - Hygiene Clean
    - Implants
    - Tooth Filling
    - Root canal
    - Tooth Extraction
    - Tooth Scale and Polish
    - X-ray
es:
  treatments:
    - Blanqueamiento
    - Obturación
    - Endodoncia
    - Extracción
    - Implante
    - Limpieza dental
    - Ortodoncia
    - Primera visita
    - Radiografía
    - Corona
    - Prótesis Removible
    - Puente Fijo
pt:
  treatments:
    - Apicectomia
    - Aparelho ortodôntico
    - Ponte
    - Coroa dentária
    - Exame odontológico
    - Prótese total
    - Primeira consulta
    - Limpeza dental
    - Implantes
    - Obturação
    - Canal
    - Extração
    - Profilaxia
    - Radiografia
